---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
- ../../apps/nsmgr
- ../../apps/registry-k8s
- ../../apps/forwarder-vpp
- ../../apps/nse-remote-vlan-vpp
- ../../apps/admission-webhook-k8s

resources:
  - device-selector.yaml

patchesStrategicMerge:
  - patch-forwarder-vpp.yaml
 
