---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-3
  labels:
    app: iperf-server-3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: iperf-server-3
  template:
    metadata:
      labels:
        app: iperf-server-3
      annotations:
        networkservicemesh.io: kernel://kernel-mech-red-trafficv6/nsm-1
    spec:
      containers:
        - name: iperf
          image: networkstatic/iperf3:latest
          imagePullPolicy: IfNotPresent
          command: ["tail", "-f", "/dev/null"]
